project:
  type: book

book:
  title: "Building Agentic Solutions with Microsoft Foundry"
  subtitle: "Patterns, Workflows, and Best Practices for Intelligent Agents"
  author: "Colby T. Ford"
  date: "09/03/2026"
  site-url: https://foundry-book.ai
  repo-url: https://github.com/colbyford/foundry-book
  cover-image: img/Building Agentic Solutions with Microsoft Foundry_cover.png
  chapters:
    - index.qmd
    # - intro.qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-link: true
    author-meta: "Colby T. Ford"

  pdf:
    documentclass: scrreprt



