project:
  type: book

book:
  title: "Building Agentic Solutions with Microsoft Foundry"
  subtitle: "Patterns, Workflows, and Best Practices for Intelligent Agents"
  author: "Colby T. Ford"
  date: "06/01/2026"
  site-url: https://foundry-book.ai
  repo-url: https://github.com/colbyford/foundry-book
  cover-image: img/cover_mockup_early_bird.png
  chapters:
    - index.qmd
    - 1_intro.qmd
    - 2_model_deployment.qmd
    - 3_model_customization.qmd
    - 4_additional_services.qmd
    - 5_agent_management.qmd
    - 6_edge_deployment.qmd
    - 7_conclusion.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-link: true
    author-meta: "Colby T. Ford"

  pdf:
    documentclass: scrreprt



